[package]
name = "modern-epfl-thesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Ali Fuat Sahin"]
license = "MIT"
description = "A sleek, modern EPFL thesis or report template for Typst."
repository = "https://github.com/alifuatsahin/epfl-thesis-template"
keywords = ["book", "academic", "epfl", "thesis"]
categories = ["paper", "report", "book"]

[template]
path = "template"
entrypoint = "main.typ"